// sample-4_explained.cpp
// Annotated, step-by-step guided copy of core logic from Reference/sample-4.cpp
// 英文思考（English reasoning）在每段前；随后给出中文详尽注释。

#include <bits/stdc++.h>
using namespace std;

// --------------------------------------------
// 0) Constants & Base Geometry (TX/TY template)
// English: The original code encodes a fixed 15-vertex polygon of a Christmas tree.
// TX/TY store template vertex coordinates. Actual tree polygon is generated by rotation+translation.
// 中文：原始代码内置圣诞树的固定 15 顶点模板坐标（TX/TY）。实际每棵树的多边形
// 通过先旋转（按角度 a），再平移到 (x,y) 获得。

static const int TV = 15; // 顶点数（Tree Vertices）
static const double TX[TV] = {
    // 英文：Placeholder for X-coordinates of template tree polygon.
    // 中文：模板树多边形的 X 坐标（此处简化；完整值见原文件）。
    -8.0, -5.5, -3.0, -1.5, 0.0, 1.5, 3.0, 5.5, 8.0, 6.0, 4.0, 2.0, 0.0, -2.0, -4.0
};
static const double TY[TV] = {
    // 英文：Placeholder for Y-coordinates of template tree polygon.
    // 中文：模板树多边形的 Y 坐标（此处简化；完整值见原文件）。
    0.0, 3.0, 6.0, 9.0, 12.0, 9.0, 6.0, 3.0, 0.0, -2.0, -3.0, -4.0, -5.0, -4.0, -3.0
};

// --------------------------------------------
// 1) Poly: Rotated + translated polygon + AABB
// English: Poly holds the rotated vertices of one tree and its axis-aligned bounding box.
// 中文：Poly 结构保存一棵树旋转+平移后的顶点，以及它的轴对齐包围盒（AABB）。
struct Poly {
    // 顶点列表（旋转后）
    array<double, TV> px; // X 坐标
    array<double, TV> py; // Y 坐标
    // 轴对齐包围盒（AABB）
    double x0, y0, x1, y1; // 左下 (x0,y0) 与右上 (x1,y1)
};

// --------------------------------------------
// 2) getPoly: Build rotated+translated polygon from (x, y, a)
// English: Given center (x,y) and angle a (radians), compute rotated vertices and AABB.
// 中文：给定树中心 (x,y) 与旋转角 a（弧度），计算旋转后的顶点和该多边形的 AABB。
static inline Poly getPoly(double x, double y, double a) {
    Poly p;
    double ca = cos(a), sa = sin(a);
    double mnx = 1e100, mny = 1e100, mxx = -1e100, mxy = -1e100;
    for (int i = 0; i < TV; ++i) {
        double rx = TX[i] * ca - TY[i] * sa;
        double ry = TX[i] * sa + TY[i] * ca;
        p.px[i] = x + rx;
        p.py[i] = y + ry;
        mnx = min(mnx, p.px[i]);
        mny = min(mny, p.py[i]);
        mxx = max(mxx, p.px[i]);
        mxy = max(mxy, p.py[i]);
    }
    p.x0 = mnx; p.y0 = mny; p.x1 = mxx; p.y1 = mxy;
    return p;
}

// --------------------------------------------
// 3) Primitive Geometry Helpers: segment intersection & point-in-polygon
// English: Ray-casting PIP; robust segment intersection for edge crossing.
// 中文：射线法的点在多边形内（PIP），以及线段相交检测，用于判定边-边穿越。

static inline int sgn(double v) { return (v > 0) - (v < 0); }

static inline double cross(double ax, double ay, double bx, double by) {
    return ax * by - ay * bx;
}

// 线段相交检测（含共线情况的基本处理）
static inline bool segInt(double ax, double ay, double bx, double by,
                         double cx, double cy, double dx, double dy) {
    auto onSeg = [](double x, double y, double x1, double y1, double x2, double y2) {
        return min(x1, x2) <= x && x <= max(x1, x2) &&
               min(y1, y2) <= y && y <= max(y1, y2);
    };

    double abx = bx - ax, aby = by - ay;
    double cdx = dx - cx, cdy = dy - cy;
    double acx = cx - ax, acy = cy - ay;

    double d1 = cross(abx, aby, acx, acy);
    double d2 = cross(abx, aby, dx - ax, dy - ay);
    double d3 = cross(cdx, cdy, ax - cx, ay - cy);
    double d4 = cross(cdx, cdy, bx - cx, by - cy);

    if ((sgn(d1) * sgn(d2) < 0) && (sgn(d3) * sgn(d4) < 0)) return true;
    if (d1 == 0 && onSeg(cx, cy, ax, ay, bx, by)) return true;
    if (d2 == 0 && onSeg(dx, dy, ax, ay, bx, by)) return true;
    if (d3 == 0 && onSeg(ax, ay, cx, cy, dx, dy)) return true;
    if (d4 == 0 && onSeg(bx, by, cx, cy, dx, dy)) return true;
    return false;
}

// 点在多边形内（射线法）
static inline bool pip(const Poly &poly, double x, double y) {
    bool inside = false;
    for (int i = 0, j = TV - 1; i < TV; j = i++) {
        double xi = poly.px[i], yi = poly.py[i];
        double xj = poly.px[j], yj = poly.py[j];
        bool intersect = ((yi > y) != (yj > y)) &&
            (x < (xj - xi) * (y - yi) / (yj - yi + 1e-18) + xi);
        if (intersect) inside = !inside;
    }
    return inside;
}

// --------------------------------------------
// 4) AABB overlap quick-reject + full polygon overlap
// English: First check axis-aligned bbox overlap; if passes, check vertices containment and edge-edge.
// 中文：先做包围盒快速剔除；若通过，再检查顶点包含与边-边相交以判重叠。
static inline bool overlap(const Poly &a, const Poly &b) {
    // AABB 快速剔除
    if (a.x1 < b.x0 || b.x1 < a.x0 || a.y1 < b.y0 || b.y1 < a.y0) return false;

    // 顶点包含：a 的任意顶点在 b 内，或 b 的任意顶点在 a 内
    for (int i = 0; i < TV; ++i) {
        if (pip(b, a.px[i], a.py[i])) return true;
        if (pip(a, b.px[i], b.py[i])) return true;
    }

    // 边-边穿越：任意边对相交
    for (int i = 0; i < TV; ++i) {
        int ni = (i + 1) % TV;
        for (int j = 0; j < TV; ++j) {
            int nj = (j + 1) % TV;
            if (segInt(a.px[i], a.py[i], a.px[ni], a.py[ni],
                       b.px[j], b.py[j], b.px[nj], b.py[nj])) return true;
        }
    }
    return false;
}

// --------------------------------------------
// 5) Configuration (Cfg): holds N trees and computations on them
// English: Cfg maintains x/y/angle arrays, per-tree Poly, and global bbox. Provides overlap checks, side length, score.
// 中文：Cfg 保存 N 棵树的 x/y/角度、每棵树的 Poly，以及全局包围盒。提供重叠检测、正方形边长与得分。
struct Cfg {
    int n;                       // 树数
    vector<double> xs, ys, as;   // 每棵树的 x, y, 角度（弧度）
    vector<Poly> polys;          // 每棵树的几何（旋转+平移）
    double gx0, gy0, gx1, gy1;   // 全局包围盒（所有树顶点的最小/最大）

    Cfg(int n_) : n(n_), xs(n_), ys(n_), as(n_), polys(n_) {}

    // 更新第 i 棵树的几何（Poly）
    void upd(int i) {
        polys[i] = getPoly(xs[i], ys[i], as[i]);
    }

    // 更新所有树的几何与全局包围盒
    void updAll() {
        double mnx = 1e100, mny = 1e100, mxx = -1e100, mxy = -1e100;
        for (int i = 0; i < n; ++i) {
            upd(i);
            mnx = min(mnx, polys[i].x0);
            mny = min(mny, polys[i].y0);
            mxx = max(mxx, polys[i].x1);
            mxy = max(mxy, polys[i].y1);
        }
        gx0 = mnx; gy0 = mny; gx1 = mxx; gy1 = mxy;
    }

    // 任意两树是否重叠（O(n^2) 检查）
    bool anyOvl() const {
        for (int i = 0; i < n; ++i)
            for (int j = i + 1; j < n; ++j)
                if (overlap(polys[i], polys[j])) return true;
        return false;
    }

    // 第 i 棵树是否与其他任意一棵重叠（用于局部搜索剪枝）
    bool hasOvl(int i) const {
        for (int j = 0; j < n; ++j) if (j != i)
            if (overlap(polys[i], polys[j])) return true;
        return false;
    }

    // 当前配置的正方形边长（以全局包围盒对齐近似）
    double side() const {
        return max(gx1 - gx0, gy1 - gy0);
    }

    // Kaggle 评分（示意）：s^2 / n
    double score() const {
        double s = side();
        return (s * s) / max(1, n);
    }

    // 收集贴近全局边界的树索引（近似）
    vector<int> getBoundary(double eps = 1e-6) const {
        vector<int> idx;
        for (int i = 0; i < n; ++i) {
            const Poly &p = polys[i];
            if (fabs(p.x0 - gx0) < eps || fabs(p.x1 - gx1) < eps ||
                fabs(p.y0 - gy0) < eps || fabs(p.y1 - gy1) < eps) {
                idx.push_back(i);
            }
        }
        return idx;
    }

    // 移除第 k 棵树，生成 n-1 配置（用于“凸出物删除-回插”策略）
    Cfg removeTree(int k) const {
        Cfg r(n - 1);
        for (int i = 0, t = 0; i < n; ++i) if (i != k) {
            r.xs[t] = xs[i]; r.ys[t] = ys[i]; r.as[t] = as[i];
            r.polys[t] = polys[i];
            ++t;
        }
        r.updAll();
        return r;
    }
};

// --------------------------------------------
// 6) Heuristics: squeeze, compaction, localSearch, edgeSlideCompaction (simplified)
// English: We only sketch simplified versions with detailed commentary.
// 中文：这里给出简化版伪实现，并配以中文详注，便于理解思路。

// squeeze：围绕全局中心做均匀缩放（示意实现：把坐标向中心按比例靠拢）
static void squeeze(Cfg &cfg, double factor = 0.98, int iters = 50) {
    cfg.updAll();
    double cx = 0.5 * (cfg.gx0 + cfg.gx1);
    double cy = 0.5 * (cfg.gy0 + cfg.gy1);
    for (int t = 0; t < iters; ++t) {
        // 英文：pull each tree slightly toward global center, recompute, stop if overlap appears.
        // 中文：将每棵树朝全局中心小幅拉近，若出现重叠则停止继续此轮。
        for (int i = 0; i < cfg.n; ++i) {
            cfg.xs[i] = cx + (cfg.xs[i] - cx) * factor;
            cfg.ys[i] = cy + (cfg.ys[i] - cy) * factor;
            cfg.upd(i);
        }
        if (cfg.anyOvl()) break;
        cfg.updAll();
    }
}

// compaction：按步长表，朝中心做可接受的小幅位移（接受准则：不重叠且 side 变小）
static void compaction(Cfg &cfg) {
    cfg.updAll();
    double best = cfg.side();
    double cx = 0.5 * (cfg.gx0 + cfg.gx1);
    double cy = 0.5 * (cfg.gy0 + cfg.gy1);
    vector<double> steps = {2.0, 1.0, 0.5, 0.25};
    for (double st : steps) {
        bool improved = true;
        while (improved) {
            improved = false;
            for (int i = 0; i < cfg.n; ++i) {
                double ox = cfg.xs[i], oy = cfg.ys[i];
                // 朝中心位移 st
                double vx = cx - cfg.xs[i], vy = cy - cfg.ys[i];
                double L = sqrt(vx * vx + vy * vy) + 1e-12;
                cfg.xs[i] += st * vx / L; cfg.ys[i] += st * vy / L; cfg.upd(i);
                cfg.updAll();
                if (!cfg.hasOvl(i) && cfg.side() < best) {
                    best = cfg.side();
                    improved = true;
                } else {
                    cfg.xs[i] = ox; cfg.ys[i] = oy; cfg.upd(i); cfg.updAll();
                }
            }
        }
    }
}

// localSearch：综合移动（朝中心、八方向微移、小角度旋转），接受不重叠且 side 降低的变化
static void localSearch(Cfg &cfg) {
    cfg.updAll();
    double best = cfg.side();
    double cx = 0.5 * (cfg.gx0 + cfg.gx1);
    double cy = 0.5 * (cfg.gy0 + cfg.gy1);
    vector<pair<double,double>> dirs = {
        {1,0},{-1,0},{0,1},{0,-1},{1,1},{1,-1},{-1,1},{-1,-1}
    };
    vector<double> shifts = {1.0, 0.5, 0.25};
    vector<double> rots = {0.0, 0.017, -0.017}; // ~1度旋转（弧度约 0.01745）
    for (int i = 0; i < cfg.n; ++i) {
        for (double sh : shifts) {
            for (auto [dx,dy] : dirs) {
                for (double ra : rots) {
                    double ox = cfg.xs[i], oy = cfg.ys[i], oa = cfg.as[i];
                    // 基于朝中心方向的复合移动（示意）
                    double vx = cx - ox, vy = cy - oy;
                    double L = sqrt(vx * vx + vy * vy) + 1e-12;
                    double mx = sh * vx / L + sh * dx;
                    double my = sh * vy / L + sh * dy;
                    cfg.xs[i] = ox + mx; cfg.ys[i] = oy + my; cfg.as[i] = oa + ra; cfg.upd(i);
                    cfg.updAll();
                    if (!cfg.hasOvl(i) && cfg.side() < best) {
                        best = cfg.side();
                    } else {
                        cfg.xs[i] = ox; cfg.ys[i] = oy; cfg.as[i] = oa; cfg.upd(i); cfg.updAll();
                    }
                }
            }
        }
    }
}

// edgeSlideCompaction：沿方向做二分滑动，直到“几乎贴边/邻居”，在不增大 side 前提下压紧外轮廓（示意）
static void edgeSlideCompaction(Cfg &cfg) {
    cfg.updAll();
    double best = cfg.side();
    vector<pair<double,double>> dirs = {{1,0},{-1,0},{0,1},{0,-1}};
    for (auto [dx,dy] : dirs) {
        for (int i = 0; i < cfg.n; ++i) {
            double ox = cfg.xs[i], oy = cfg.ys[i];
            // 二分搜索的步长（示意）：尝试在该方向更靠近外轮廓或邻居
            double low = 0.0, high = 8.0; // 最大滑动幅度示意
            for (int it = 0; it < 20; ++it) {
                double mid = 0.5 * (low + high);
                cfg.xs[i] = ox + dx * mid; cfg.ys[i] = oy + dy * mid; cfg.upd(i);
                cfg.updAll();
                bool ok = !cfg.hasOvl(i) && cfg.side() <= best;
                if (ok) {
                    low = mid; best = cfg.side();
                } else {
                    high = mid;
                }
            }
            // 最终落点：low
            cfg.xs[i] = ox + dx * low; cfg.ys[i] = oy + dy * low; cfg.upd(i); cfg.updAll();
        }
    }
}

// --------------------------------------------
// 7) Minimal demo main (non-competitive): shows how to wire pieces together
// 中文：仅演示如何串联各模块（非竞赛用）。实际完整实现请参考原文件。
int main() {
    // 构造一个简单配置，包含 3 棵树（示例）
    Cfg cfg(3);
    cfg.xs = {0.0, 10.0, -10.0};
    cfg.ys = {0.0, 0.0, 0.0};
    cfg.as = {0.0, 0.2, -0.2};
    cfg.updAll();

    cout << "Initial side: " << cfg.side() << endl;
    cout << "Any overlap? " << (cfg.anyOvl() ? "yes" : "no") << endl;

    // 逐步启发式示例：
    squeeze(cfg);
    cout << "After squeeze side: " << cfg.side() << endl;

    compaction(cfg);
    cout << "After compaction side: " << cfg.side() << endl;

    localSearch(cfg);
    cout << "After localSearch side: " << cfg.side() << endl;

    edgeSlideCompaction(cfg);
    cout << "After edgeSlideCompaction side: " << cfg.side() << endl;

    // 输出最终示意得分（非严格 Kaggle 评分）
    cout << "Final score (approx): " << cfg.score() << endl;
    return 0;
}
